"""upgrade_1

Revision ID: 9ae0df370942
Revises: 29f8cba153b2
Create Date: 2025-08-09 20:56:38.378924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9ae0df370942'
down_revision: Union[str, Sequence[str], None] = '29f8cba153b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('validity_hours', sa.Integer(), nullable=False))
    op.add_column('package', sa.Column('speed_limit', sa.Float(), nullable=False))
    op.add_column('package', sa.Column('mikrotik_profile_name', sa.String(), nullable=True))
    op.add_column('package', sa.Column('is_synced', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_package_mikrotik_profile_name'), 'package', ['mikrotik_profile_name'], unique=True)
    op.drop_column('package', 'quantity_mbps')
    op.drop_column('package', 'speed_mbps')
    op.drop_column('package', 'duration_minutes')
    op.drop_column('package', 'period')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('period', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('package', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('package', sa.Column('speed_mbps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('package', sa.Column('quantity_mbps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_package_mikrotik_profile_name'), table_name='package')
    op.drop_column('package', 'is_synced')
    op.drop_column('package', 'mikrotik_profile_name')
    op.drop_column('package', 'speed_limit')
    op.drop_column('package', 'validity_hours')
    # ### end Alembic commands ###
