"""add_statut_in_all_table

Revision ID: ae72b0e4f27d
Revises: e4c0f749fcd2
Create Date: 2025-09-03 12:03:18.195977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ae72b0e4f27d'
down_revision: Union[str, Sequence[str], None] = 'e4c0f749fcd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('statut', sa.String(), nullable=False))
    op.add_column('transaction', sa.Column('statut', sa.String(), nullable=False))
    op.add_column('voucher', sa.Column('statut', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voucher', 'statut')
    op.drop_column('transaction', 'statut')
    op.drop_column('package', 'statut')
    # ### end Alembic commands ###
