"""add statut column to user

Revision ID: e081c471b6fb
Revises: 4b79b4d13552
Create Date: 2025-08-25 11:51:29.096698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e081c471b6fb'
down_revision: Union[str, Sequence[str], None] = '4b79b4d13552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('user', sa.Column('statut', sa.String(), nullable=False))
    op.add_column('user', sa.Column('role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('user', 'statut')
    op.alter_column('transaction', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
